<!DOCTYPE html>

<html dir="ltr" lang="en-US">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/bootstrap-theme.min.css">
<link rel="stylesheet" href="css/main.css">
<script src="js/vendor/modernizr-2.6.2.min.js"></script>

<script type="text/javascript">
function loadUrl(newLocation)
{
top.location = newLocation;
}
</script>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#" onclick="loadUrl('index.html')">ELVIS Project</a>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        <li><a href="#" onclick="loadUrl('')">Framework</a></li>
        <li><a href="#" onclick="loadUrl('')">Web App</a></li>
        <li><a href="#" onclick="loadUrl('')">Database</a></li>
        <li><a href="#" onclick="loadUrl('')">Research</a></li>
        </ul>
    </div><!--/.navbar-collapse -->
    </div>
</div>
</html>
